import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import { SessionProvider } from "./context/SessionContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fashion Nova Lingerie Shop",
  description: "Generated by the best developer in Antarctica",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <SessionProvider>

          <Header/>
        <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[radial-gradient(125%_125%_at_50%_10%,#ffffff_40%,#63e_100%)]">
          {children}
          
        </div>
        </SessionProvider>
      </body>
    </html>
  );
}
